sonar.projectKey=kroos2211_testsonar
sonar.sources=.

sonar.token=05a883cf432a4f9166261fc78954716ece8683d2

sonar.sourceEncoding=UTF-8

sonar.java.binaries=target

sonar.host.url=https://sonarcloud.io

sonar.organization=kroos2211

